services:
  dolt:
    image: dolthub/dolt-sql-server:latest
    volumes:
      - /Users/bedwards/.doltdb:/var/lib/dolt
    ports:
      - "127.0.0.1:3307:3306"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  studio:
    build:
      context: ./nix-docker
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - /Users/bedwards/claude-sandbox:/home/dev/workspace
#    stdin_open: true
#    tty: true
    restart: unless-stopped
