[SERVICE]
    flush        5
    daemon       off
    log_level    warn

[INPUT]
    name         tail
    path         /var/lib/docker/containers/*/*.log
    parser       docker
    tag          docker.*
    read_from_head false
    refresh_interval 10
    mem_buf_limit 5MB
    skip_long_lines on

[FILTER]
    name         modify
    match        docker.*
    remove       stream

[OUTPUT]
    name         http
    match        docker.*
    host         openobserve
    port         5080
    uri          /api/3ANT9xNeShmoldeVfO1ZlOblRjw/docker_logs/_json
    format       json
    json_date_key _timestamp
    json_date_format iso8601
    http_user    fluent-bit@mail.hosaka.io
    http_passwd  FUeSfQxQIbr5WeV8
    tls          off
    compress     gzip
