[default]
server_host = "0.0.0.0"
server_port = 8000
jwt_expiry_days = 90
auth_code_expiry_minutes = 10
cookie_secure = false

[default.cors]
allow_origins = ["*"]
allow_credentials = true

[default.mailgun]
domain = "sandbox5ef17532b595421ba4c35386a9b09f11.mailgun.org"
from_email = "Mailgun Sandbox <postmaster@sandbox5ef17532b595421ba4c35386a9b09f11.mailgun.org>"

[default.db]
host = "localhost"
port = 5433
name = "moods"
user = "moods"
password = "moods"

[default.otel]
endpoint = ""
service_name = "moods"

[development]
dynaconf_merge = true
cookie_secure = true

[development.cors]
allow_origins = ["https://moods-dev.hosaka.io"]
allow_credentials = false

[development.db]
host = "db"
port = 5432
name = "moods_dev"
user = "moods_dev"
password = "moods_dev"

[development.otel]
endpoint = "http://openobserve:5080/api/3ANT9xNeShmoldeVfO1ZlOblRjw/"
service_name = "moods-dev"

[production]
dynaconf_merge = true
cookie_secure = true

[production.cors]
allow_origins = ["https://moods.hosaka.io"]
allow_credentials = false

[production.db]
host = "db"
port = 5432

[production.otel]
endpoint = "http://openobserve:5080/api/production/"
service_name = "moods-prod"

[testing]
dynaconf_merge = true
jwt_secret = "test-secret-do-not-use-in-production-minimum-32-bytes-long"

[testing.db]
name = "moods_test"
